// <auto-generated />
using System;
using EcoRestore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoRestore.Migrations
{
    [DbContext(typeof(EcoRestoreDbContext))]
    [Migration("20260701101611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoRestore.Models.Fauna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateZone")
                        .HasColumnType("integer");

                    b.Property<string>("HabitatNotes")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Faunas");
                });

            modelBuilder.Entity("EcoRestore.Models.PlantingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfTrees")
                        .HasColumnType("integer");

                    b.Property<int>("PlotId")
                        .HasColumnType("integer");

                    b.Property<int>("TreeSpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.HasIndex("TreeSpeciesId");

                    b.ToTable("PlantingPlans");
                });

            modelBuilder.Entity("EcoRestore.Models.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaHectares")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SoilTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("EcoRestore.Models.SoilType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FertilityRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecommendedAmendment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoilTypes");
                });

            modelBuilder.Entity("EcoRestore.Models.TreeSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CO2SequestrationKgPerYear")
                        .HasColumnType("numeric");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("integer");

                    b.Property<int>("GrowthRateCategory")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TreeSpecies");
                });

            modelBuilder.Entity("FaunaPlantingPlan", b =>
                {
                    b.Property<int>("PlantingPlansId")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedFaunaId")
                        .HasColumnType("integer");

                    b.HasKey("PlantingPlansId", "SuggestedFaunaId");

                    b.HasIndex("SuggestedFaunaId");

                    b.ToTable("FaunaPlantingPlan");
                });

            modelBuilder.Entity("EcoRestore.Models.PlantingPlan", b =>
                {
                    b.HasOne("EcoRestore.Models.Plot", "Plot")
                        .WithMany("PlantingPlans")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRestore.Models.TreeSpecies", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("EcoRestore.Models.Plot", b =>
                {
                    b.HasOne("EcoRestore.Models.SoilType", "SoilType")
                        .WithMany()
                        .HasForeignKey("SoilTypeId");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("FaunaPlantingPlan", b =>
                {
                    b.HasOne("EcoRestore.Models.PlantingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlantingPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoRestore.Models.Fauna", null)
                        .WithMany()
                        .HasForeignKey("SuggestedFaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoRestore.Models.Plot", b =>
                {
                    b.Navigation("PlantingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
